root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/web"
bin = "./tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html", "css", "js"]
exclude_dir = ["tmp", "vendor"]
exclude_file = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = false
follow_symlink = false
delay = 1000
stop_on_root = false
send_interrupt = false
kill_delay = 500
log = "build-errors.log"

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[log]
time = true

[misc]
clean_on_exit = true
